#############################################################################
# Makefile for building: test.app/Contents/MacOS/test
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  test.pro
# Template: app
# Command: /Users/GODLZR/Applications/Qt5.3/5.3/clang_64/bin/qmake -spec macx-xcode -o test.xcodeproj/project.pbxproj test.pro
#############################################################################

MAKEFILE      = project.pbxproj

MOC       = /Users/GODLZR/Applications/Qt5.3/5.3/clang_64/bin/moc
UIC       = /Users/GODLZR/Applications/Qt5.3/5.3/clang_64/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_TESTLIB_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR=\"/Users/GODLZR/Workspace/Xcode_Workspace/HST\"
INCPATH       = -I../../../Applications/Qt5.3/5.3/clang_64/mkspecs/macx-clang -I. -I/usr/local/include -I/usr/local/include/opencv -I/usr/local/include/opencv2 -I../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../../Applications/Qt5.3/5.3/clang_64/lib/QtTest.framework/Versions/5/Headers -I../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -F/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib
DEL_FILE  = rm -f
MOVE      = mv -f

IMAGES = 
PARSERS =
preprocess: $(PARSERS) compilers
clean preprocess_clean: parser_clean compiler_clean

parser_clean:
mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compilers: moc_mainwindow.cpp moc_imageviewer.cpp ui_mainwindow.h
compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_imageviewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_imageviewer.cpp
moc_mainwindow.cpp: /usr/local/include/opencv/cv.h \
		/usr/local/include/opencv/highgui.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QPoint \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		croprect.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		imageviewer.h \
		cvimage.h \
		gabor.h \
		enhancedgabor.h \
		mainwindow.h
	/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/mkspecs/macx-clang -I/Users/GODLZR/Workspace/Xcode_Workspace/HST -I/usr/local/include -I/usr/local/include/opencv -I/usr/local/include/opencv2 -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtTest.framework/Headers -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_imageviewer.cpp: /usr/local/include/opencv/cv.h \
		/usr/local/include/opencv/highgui.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		croprect.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QPoint \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		imageviewer.h
	/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/mkspecs/macx-clang -I/Users/GODLZR/Workspace/Xcode_Workspace/HST -I/usr/local/include -I/usr/local/include/opencv -I/usr/local/include/opencv2 -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtTest.framework/Headers -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib imageviewer.h -o moc_imageviewer.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

