#############################################################################
# Makefile for building: test.app/Contents/MacOS/test
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  test.pro
# Template: app
# Command: /Users/GODLZR/Applications/Qt5.3/5.3/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o makefile test.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_TESTLIB_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR=\"/Users/GODLZR/Workspace/Xcode_Workspace/HST\"
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.10 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.10 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../Applications/Qt5.3/5.3/clang_64/mkspecs/macx-clang -I. -I/usr/local/include -I/usr/local/include/opencv -I/usr/local/include/opencv2 -I../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../../Applications/Qt5.3/5.3/clang_64/lib/QtTest.framework/Versions/5/Headers -I../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -F/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.10
LIBS          = $(SUBLIBS) -F/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib -L/usr/local/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_calib3d -lopencv_contrib -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_legacy -lopencv_ml -lopencv_objdetect -lopencv_video -framework QtWidgets -framework QtGui -framework QtCore -framework QtTest -framework Security -framework ApplicationServices -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/GODLZR/Applications/Qt5.3/5.3/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		imageviewer.cpp \
		cvimage.cpp \
		gabor.cpp \
		enhancedgabor.cpp \
		matlabhelper.cpp moc_mainwindow.cpp \
		moc_imageviewer.cpp
OBJECTS       = main.o \
		mainwindow.o \
		imageviewer.o \
		cvimage.o \
		gabor.o \
		enhancedgabor.o \
		matlabhelper.o \
		moc_mainwindow.o \
		moc_imageviewer.o
DIST          = ../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/qdevice.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/device_config.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/unix.conf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/mac.conf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/macx.conf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/clang.conf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/clang-mac.conf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/qconfig.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/default_post.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/qt.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/resources.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/moc.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/testlib_defines.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/uic.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/yacc.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/lex.prf \
		test.pro main.cpp \
		mainwindow.cpp \
		imageviewer.cpp \
		cvimage.cpp \
		gabor.cpp \
		enhancedgabor.cpp \
		matlabhelper.cpp
QMAKE_TARGET  = test
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = test.app/Contents/MacOS/test

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-mmacosx-version-min=10.10 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: makefile test.app/Contents/PkgInfo test.app/Contents/Resources/empty.lproj test.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d test.app/Contents/MacOS/ || mkdir -p test.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

makefile: test.pro ../../../Applications/Qt5.3/5.3/clang_64/mkspecs/macx-clang/qmake.conf ../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/qdevice.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/device_config.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/unix.conf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/mac.conf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/macx.conf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/clang.conf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/clang-mac.conf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/qconfig.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/default_post.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/qt.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/resources.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/moc.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/testlib_defines.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/uic.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/yacc.prf \
		../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/lex.prf \
		test.pro \
		/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtTest.framework/QtTest.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o makefile test.pro
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/spec_pre.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/qdevice.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/device_config.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/shell-unix.conf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/unix.conf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/mac.conf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/macx.conf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/gcc-base.conf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/clang.conf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/common/clang-mac.conf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/qconfig.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/qt_functions.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/qt_config.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/default_pre.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/resolve_config.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/default_post.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/mac/sdk.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/mac/default_post.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/warn_on.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/qt.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/resources.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/moc.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/unix/opengl.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/testlib_defines.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/uic.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/unix/thread.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/mac/rez.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/testcase_targets.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/exceptions.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/yacc.prf:
../../../Applications/Qt5.3/5.3/clang_64/mkspecs/features/lex.prf:
test.pro:
/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtTest.framework/QtTest.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o makefile test.pro

qmake_all: FORCE

test.app/Contents/PkgInfo: 
	@test -d test.app/Contents || mkdir -p test.app/Contents
	@$(DEL_FILE) test.app/Contents/PkgInfo
	@echo "APPL????" >test.app/Contents/PkgInfo
test.app/Contents/Resources/empty.lproj: 
	@test -d test.app/Contents/Resources || mkdir -p test.app/Contents/Resources
	@touch test.app/Contents/Resources/empty.lproj
	
test.app/Contents/Info.plist: 
	@test -d test.app/Contents || mkdir -p test.app/Contents
	@$(DEL_FILE) test.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,GODLZR.test,g" -e "s,@EXECUTABLE@,test,g" -e "s,@TYPEINFO@,????,g" ../../../Applications/Qt5.3/5.3/clang_64/mkspecs/macx-clang/Info.plist.app >test.app/Contents/Info.plist
dist: 
	@test -d .tmp/test1.0.0 || mkdir -p .tmp/test1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/test1.0.0/ && $(COPY_FILE) --parents mainwindow.h croprect.h imageviewer.h cvimage.h gabor.h enhancedgabor.h matlabhelper.h .tmp/test1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp imageviewer.cpp cvimage.cpp gabor.cpp enhancedgabor.cpp matlabhelper.cpp .tmp/test1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/test1.0.0/ && (cd `dirname .tmp/test1.0.0` && $(TAR) test1.0.0.tar test1.0.0 && $(COMPRESS) test1.0.0.tar) && $(MOVE) `dirname .tmp/test1.0.0`/test1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/test1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r test.app
	-$(DEL_FILE) makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_imageviewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_imageviewer.cpp
moc_mainwindow.cpp: /usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv/highgui.h \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QPoint \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		croprect.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		imageviewer.h \
		cvimage.h \
		gabor.h \
		matlabhelper.h \
		enhancedgabor.h \
		imageDisplayer.h \
		mainwindow.h
	/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/mkspecs/macx-clang -I/Users/GODLZR/Workspace/Xcode_Workspace/HST -I/usr/local/include -I/usr/local/include/opencv -I/usr/local/include/opencv2 -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtTest.framework/Headers -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_imageviewer.cpp: /usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv/highgui.h \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		croprect.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QPoint \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		imageviewer.h
	/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/mkspecs/macx-clang -I/Users/GODLZR/Workspace/Xcode_Workspace/HST -I/usr/local/include -I/usr/local/include/opencv -I/usr/local/include/opencv2 -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtTest.framework/Headers -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/lib imageviewer.h -o moc_imageviewer.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/GODLZR/Applications/Qt5.3/5.3/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv/highgui.h \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QPoint \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		croprect.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		imageviewer.h \
		cvimage.h \
		gabor.h \
		matlabhelper.h \
		enhancedgabor.h \
		imageDisplayer.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv/highgui.h \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QPoint \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		croprect.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		imageviewer.h \
		cvimage.h \
		gabor.h \
		matlabhelper.h \
		enhancedgabor.h \
		imageDisplayer.h \
		ui_mainwindow.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextCodec \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextcodec.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

imageviewer.o: imageviewer.cpp imageviewer.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv/highgui.h \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		croprect.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QPoint \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imageviewer.o imageviewer.cpp

cvimage.o: cvimage.cpp cvimage.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv/highgui.h \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		gabor.h \
		matlabhelper.h \
		enhancedgabor.h \
		imageDisplayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cvimage.o cvimage.cpp

gabor.o: gabor.cpp gabor.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv/highgui.h \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		matlabhelper.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gabor.o gabor.cpp

enhancedgabor.o: enhancedgabor.cpp enhancedgabor.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv/highgui.h \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		imageDisplayer.h \
		matlabhelper.h \
		../../../Applications/Qt5.3/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enhancedgabor.o enhancedgabor.cpp

matlabhelper.o: matlabhelper.cpp matlabhelper.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv/highgui.h \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o matlabhelper.o matlabhelper.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_imageviewer.o: moc_imageviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imageviewer.o moc_imageviewer.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

